spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/deproject
    username: xogur
    password: xogur
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000