spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/deproject
    # url: jdbc:postgresql://postgres_custom:5432/deproject
    username: xogur
    password: xogur
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8000

aes:
  secret: 'f7Tg9Kw3sXp1LmZa'